# Generated by Django 3.1.5 on 2021-02-15 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210126_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
