# Generated by Django 3.1.5 on 2021-02-15 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210215_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
