# Generated by Django 3.1.5 on 2021-02-18 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210215_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
